include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    constant_identifier_names: false
    non_constant_identifier_names: false
    prefer_single_quotes: true
    use_super_parameters: false
