targets:
  $default:
    builders:
      freezed:
        generate_for:
          - example/**.dart
          - lib/**.dart
          - test/shared/shared_test_utils.dart
      json_serializable:
        options:
          any_map: true
          explicit_to_json: true
        generate_for:
          - example/**.dart
          - lib/**.dart
          - test/shared/shared_test_utils.dart
